"""
LLM Provider Configuration Registry

Discovers available models per provider via a bundled static catalogue
(generated by scripts/generate_model_catalogue.py) and runtime calls to
any-llm's list_models. Provides friendly labels via the OpenRouter cache.
"""

from typing import List, Dict, Optional, TypedDict
import time
import json
import re
from pathlib import Path

import logging
_logger = logging.getLogger(__name__)

try:
    import any_llm
    HAS_ANY_LLM = True
    _logger.info("[LLM] any-llm imported successfully")
except ImportError as e:
    HAS_ANY_LLM = False
    _logger.error(f"[LLM] any-llm import failed: {e}")
    import traceback
    _logger.error(f"[LLM] Import traceback:\n{traceback.format_exc()}")

# In-memory cache for model display names
_model_display_names: Dict[str, str] = {}
_display_names_loaded: bool = False

# OpenRouter API for fetching pretty model names
OPENROUTER_MODELS_URL = "https://openrouter.ai/api/v1/models"
CACHE_MAX_AGE_DAYS = 7


class ModelInfo(TypedDict):
    value: str      # Model ID for API calls
    label: str      # Display name in UI


class ProviderInfo(TypedDict):
    name: str                   # Display name
    kind: str                   # "hosted" | "local"
    key_prefix: str             # Expected API key prefix (for validation hints); "" for local
    key_placeholder: str        # Placeholder text for API key input; "" for local
    env_var: str                # Environment variable for API key; "" for local
    any_llm_provider: str       # any-llm provider key for model lookup
    base_url_default: str       # Default base URL for local runtimes; "" for hosted


# Provider metadata. Hosted providers use an API key; local providers use a base URL.
# Models for hosted providers come from data/model_catalogue.json (bundled).
# Models for local providers are queried at runtime via any_llm.list_models.
PROVIDERS: Dict[str, ProviderInfo] = {
    # === Hosted (single API key) ===
    "anthropic": {
        "name": "Anthropic (Claude)",
        "kind": "hosted",
        "key_prefix": "sk-ant-",
        "key_placeholder": "sk-ant-...",
        "env_var": "ANTHROPIC_API_KEY",
        "any_llm_provider": "anthropic",
        "base_url_default": "",
    },
    "openai": {
        "name": "OpenAI (GPT)",
        "kind": "hosted",
        "key_prefix": "sk-",
        "key_placeholder": "sk-...",
        "env_var": "OPENAI_API_KEY",
        "any_llm_provider": "openai",
        "base_url_default": "",
    },
    "gemini": {
        "name": "Google (Gemini)",
        "kind": "hosted",
        "key_prefix": "AI",
        "key_placeholder": "AIza...",
        "env_var": "GEMINI_API_KEY",
        "any_llm_provider": "gemini",
        "base_url_default": "",
    },
    "mistral": {
        "name": "Mistral AI",
        "kind": "hosted",
        "key_prefix": "",
        "key_placeholder": "API key...",
        "env_var": "MISTRAL_API_KEY",
        "any_llm_provider": "mistral",
        "base_url_default": "",
    },
    "groq": {
        "name": "Groq (Fast Inference)",
        "kind": "hosted",
        "key_prefix": "gsk_",
        "key_placeholder": "gsk_...",
        "env_var": "GROQ_API_KEY",
        "any_llm_provider": "groq",
        "base_url_default": "",
    },
    "xai": {
        "name": "xAI (Grok)",
        "kind": "hosted",
        "key_prefix": "xai-",
        "key_placeholder": "xai-...",
        "env_var": "XAI_API_KEY",
        "any_llm_provider": "xai",
        "base_url_default": "",
    },
    "cohere": {
        "name": "Cohere",
        "kind": "hosted",
        "key_prefix": "",
        "key_placeholder": "API key...",
        "env_var": "COHERE_API_KEY",
        "any_llm_provider": "cohere",
        "base_url_default": "",
    },
    "together": {
        "name": "Together AI",
        "kind": "hosted",
        "key_prefix": "",
        "key_placeholder": "API key...",
        "env_var": "TOGETHER_API_KEY",
        "any_llm_provider": "together",
        "base_url_default": "",
    },
    "deepseek": {
        "name": "DeepSeek",
        "kind": "hosted",
        "key_prefix": "sk-",
        "key_placeholder": "sk-...",
        "env_var": "DEEPSEEK_API_KEY",
        "any_llm_provider": "deepseek",
        "base_url_default": "",
    },
    "openrouter": {
        "name": "OpenRouter",
        "kind": "hosted",
        "key_prefix": "sk-or-",
        "key_placeholder": "sk-or-...",
        "env_var": "OPENROUTER_API_KEY",
        "any_llm_provider": "openrouter",
        "base_url_default": "",
    },
    "perplexity": {
        "name": "Perplexity",
        "kind": "hosted",
        "key_prefix": "pplx-",
        "key_placeholder": "pplx-...",
        "env_var": "PERPLEXITY_API_KEY",
        "any_llm_provider": "perplexity",
        "base_url_default": "",
    },
    "fireworks": {
        "name": "Fireworks AI",
        "kind": "hosted",
        "key_prefix": "",
        "key_placeholder": "API key...",
        "env_var": "FIREWORKS_API_KEY",
        "any_llm_provider": "fireworks",
        "base_url_default": "",
    },
    "cerebras": {
        "name": "Cerebras",
        "kind": "hosted",
        "key_prefix": "csk-",
        "key_placeholder": "csk-...",
        "env_var": "CEREBRAS_API_KEY",
        "any_llm_provider": "cerebras",
        "base_url_default": "",
    },
    "sambanova": {
        "name": "SambaNova",
        "kind": "hosted",
        "key_prefix": "",
        "key_placeholder": "API key...",
        "env_var": "SAMBANOVA_API_KEY",
        "any_llm_provider": "sambanova",
        "base_url_default": "",
    },
    "moonshot": {
        "name": "Moonshot (Kimi)",
        "kind": "hosted",
        "key_prefix": "sk-",
        "key_placeholder": "sk-...",
        "env_var": "MOONSHOT_API_KEY",
        "any_llm_provider": "moonshot",
        "base_url_default": "",
    },
    "nebius": {
        "name": "Nebius AI Studio",
        "kind": "hosted",
        "key_prefix": "",
        "key_placeholder": "API key...",
        "env_var": "NEBIUS_API_KEY",
        "any_llm_provider": "nebius",
        "base_url_default": "",
    },
    "huggingface": {
        "name": "HuggingFace Inference",
        "kind": "hosted",
        "key_prefix": "hf_",
        "key_placeholder": "hf_...",
        "env_var": "HF_TOKEN",
        "any_llm_provider": "huggingface",
        "base_url_default": "",
    },
    "zai": {
        "name": "z.ai (GLM)",
        "kind": "hosted",
        "key_prefix": "",
        "key_placeholder": "API key...",
        "env_var": "ZAI_API_KEY",
        "any_llm_provider": "zai",
        "base_url_default": "",
    },
    # === Local runtimes (no API key, configured by base URL) ===
    "ollama": {
        "name": "Ollama (local)",
        "kind": "local",
        "key_prefix": "",
        "key_placeholder": "",
        "env_var": "",
        "any_llm_provider": "ollama",
        "base_url_default": "http://localhost:11434",
    },
    "lmstudio": {
        "name": "LM Studio (local)",
        "kind": "local",
        "key_prefix": "",
        "key_placeholder": "",
        "env_var": "",
        "any_llm_provider": "lmstudio",
        "base_url_default": "http://localhost:1234/v1",
    },
    "llamacpp": {
        "name": "llama.cpp server (local)",
        "kind": "local",
        "key_prefix": "",
        "key_placeholder": "",
        "env_var": "",
        "any_llm_provider": "llamacpp",
        "base_url_default": "http://localhost:8080",
    },
    "llamafile": {
        "name": "llamafile (local)",
        "kind": "local",
        "key_prefix": "",
        "key_placeholder": "",
        "env_var": "",
        "any_llm_provider": "llamafile",
        "base_url_default": "http://localhost:8080",
    },
    "vllm": {
        "name": "vLLM (local)",
        "kind": "local",
        "key_prefix": "",
        "key_placeholder": "",
        "env_var": "",
        "any_llm_provider": "vllm",
        "base_url_default": "http://localhost:8000/v1",
    },
}


# =============================================================================
# Model Display Name Functions (OpenRouter API)
# =============================================================================

def _get_cache_path() -> Path:
    """Get the cache file path for OpenRouter models."""
    from ..core import paths
    return paths.get_path_manager().get_openrouter_models_cache_path()


def _load_display_names_from_cache() -> Dict[str, str]:
    """Load model display names from cache file if valid."""
    cache_path = _get_cache_path()

    if not cache_path.exists():
        return {}

    try:
        # Check cache age
        file_age_days = (time.time() - cache_path.stat().st_mtime) / 86400
        if file_age_days > CACHE_MAX_AGE_DAYS:
            _logger.info(f"[LLM] OpenRouter cache expired ({file_age_days:.1f} days old)")
            return {}

        with open(cache_path, 'r', encoding='utf-8') as f:
            data = json.load(f)
            _logger.info(f"[LLM] Loaded {len(data)} model display names from cache")
            return data
    except Exception as e:
        _logger.warning(f"[LLM] Failed to load display names cache: {e}")
        return {}


def _save_display_names_to_cache(names: Dict[str, str]) -> None:
    """Save model display names to cache file."""
    cache_path = _get_cache_path()

    try:
        cache_path.parent.mkdir(parents=True, exist_ok=True)
        with open(cache_path, 'w', encoding='utf-8') as f:
            json.dump(names, f, indent=2)
        _logger.info(f"[LLM] Saved {len(names)} model display names to cache")
    except Exception as e:
        _logger.warning(f"[LLM] Failed to save display names cache: {e}")


def _fetch_display_names_from_api() -> Dict[str, str]:
    """Fetch model display names from OpenRouter API."""
    import urllib.request
    import ssl

    try:
        _logger.info("[LLM] Fetching model names from OpenRouter API...")

        # Create request with timeout
        request = urllib.request.Request(
            OPENROUTER_MODELS_URL,
            headers={'User-Agent': 'letmelcthatforyou/1.0'}
        )

        # Use default SSL context
        context = ssl.create_default_context()

        with urllib.request.urlopen(request, timeout=10, context=context) as response:
            data = json.loads(response.read().decode('utf-8'))

        # Parse response: {"data": [{"id": "anthropic/claude-3-opus", "name": "Claude 3 Opus", ...}, ...]}
        names = {}
        for model in data.get('data', []):
            model_id = model.get('id', '')
            model_name = model.get('name', '')
            if model_id and model_name:
                names[model_id] = model_name

        _logger.info(f"[LLM] Fetched {len(names)} model names from OpenRouter")
        return names

    except Exception as e:
        _logger.warning(f"[LLM] Failed to fetch from OpenRouter API: {e}")
        return {}


def get_model_display_names() -> Dict[str, str]:
    """
    Get mapping of model IDs to human-readable display names.

    Uses caching strategy:
    1. Return in-memory cache if already loaded
    2. Load from local cache file if exists and < 7 days old
    3. Fetch from OpenRouter API and save to cache
    4. Graceful fallback: returns empty dict if all fails (raw IDs used as fallback)

    Returns:
        Dict mapping model IDs to display names (e.g., {"anthropic/claude-3-opus": "Claude 3 Opus"})
    """
    global _model_display_names, _display_names_loaded

    # Return cached if already loaded this session
    if _display_names_loaded:
        return _model_display_names

    # Try loading from file cache
    _model_display_names = _load_display_names_from_cache()

    if _model_display_names:
        _display_names_loaded = True
        return _model_display_names

    # Fetch from API
    _model_display_names = _fetch_display_names_from_api()

    if _model_display_names:
        _save_display_names_to_cache(_model_display_names)
        _display_names_loaded = True

    return _model_display_names


def _parse_model_id_to_display_name(model_id: str) -> str:
    """
    Parse a raw model ID into a human-readable display name.

    Handles patterns like:
    - anthropic/claude-opus-4-5-20251101 → Claude Opus 4.5
    - anthropic/claude-3-haiku-20240307 → Claude 3 Haiku
    - openai/gpt-4o-2024-08-06 → Gpt 4o
    - mistral/mistral-large-2411 → Mistral Large

    Args:
        model_id: Raw model ID (e.g., "anthropic/claude-opus-4-5-20251101")

    Returns:
        Human-readable display name
    """
    # Remove provider prefix if present
    if '/' in model_id:
        model_id = model_id.split('/', 1)[1]

    # Remove date suffix (8 digits at end, optionally preceded by hyphen)
    model_id = re.sub(r'-?\d{8}$', '', model_id)
    # Also handle YYMM format like mistral-large-2411
    model_id = re.sub(r'-\d{4}$', '', model_id)

    # Split into parts
    parts = model_id.split('-')

    # Process version numbers: look for patterns like "4-5" (meaning 4.5) or "4-1" (meaning 4.1)
    processed_parts = []
    i = 0
    while i < len(parts):
        part = parts[i]

        # Check if this is a single digit that might be a major version
        if part.isdigit() and len(part) == 1:
            # Check if next part is also a single digit (minor version)
            if i + 1 < len(parts) and parts[i + 1].isdigit() and len(parts[i + 1]) == 1:
                # Combine as version: "4" + "5" → "4.5"
                processed_parts.append(f"{part}.{parts[i + 1]}")
                i += 2
                continue
            else:
                # Just a major version: "4" or "3"
                processed_parts.append(part)
        else:
            # Regular word - title case it
            processed_parts.append(part.title())
        i += 1

    return ' '.join(processed_parts)


def get_display_name(model_id: str) -> str:
    """
    Get human-readable display name for a model ID.

    Args:
        model_id: Raw model ID (e.g., "claude-3-opus-20240229" or "anthropic/claude-3-opus")

    Returns:
        Display name if found, otherwise a parsed version of the model_id.
    """
    names = get_model_display_names()

    # Direct match
    if model_id in names:
        return names[model_id]

    # Try with common provider prefixes
    for prefix in ['anthropic/', 'openai/', 'google/', 'mistral/', 'meta-llama/', 'cohere/']:
        prefixed_id = f"{prefix}{model_id}"
        if prefixed_id in names:
            return names[prefixed_id]

    # Fallback: parse the model ID into a readable name
    return _parse_model_id_to_display_name(model_id)


# =============================================================================
# Provider Functions
# =============================================================================

def get_available_providers() -> List[Dict[str, str]]:
    """Get list of available providers for UI dropdown."""
    return [
        {"value": key, "label": info["name"]}
        for key, info in PROVIDERS.items()
    ]


# =============================================================================
# Static Model Catalogue (bundled at build time)
# =============================================================================

# Catalogue shape: {provider_key: {model_id: {"context_window": int|None}}}
_MODEL_CATALOGUE: Optional[Dict[str, Dict[str, Dict[str, object]]]] = None


def _get_catalogue_path() -> Path:
    """Locate the bundled model_catalogue.json. Works in both source and frozen builds."""
    import sys
    if getattr(sys, "frozen", False):
        # PyInstaller: bundled under data/ in _MEIPASS
        return Path(sys._MEIPASS) / "data" / "model_catalogue.json"  # type: ignore[attr-defined]
    # Source layout: letmelcthatforyou/data/model_catalogue.json
    return Path(__file__).resolve().parents[3] / "data" / "model_catalogue.json"


def _load_model_catalogue() -> Dict[str, Dict[str, Dict[str, object]]]:
    """Load the bundled model catalogue once and cache it in memory."""
    global _MODEL_CATALOGUE
    if _MODEL_CATALOGUE is not None:
        return _MODEL_CATALOGUE

    path = _get_catalogue_path()
    if not path.exists():
        _logger.warning(f"[LLM] Model catalogue not found at {path}")
        _MODEL_CATALOGUE = {}
        return _MODEL_CATALOGUE

    try:
        with open(path, "r", encoding="utf-8") as f:
            _MODEL_CATALOGUE = json.load(f)
        total = sum(len(v) for v in _MODEL_CATALOGUE.values())
        _logger.info(f"[LLM] Loaded model catalogue: {total} models across {len(_MODEL_CATALOGUE)} providers")
    except Exception as e:
        _logger.error(f"[LLM] Failed to load model catalogue: {e}")
        _MODEL_CATALOGUE = {}

    return _MODEL_CATALOGUE


def get_model_context_window(provider: str, model_id: str) -> Optional[int]:
    """Look up a model's context window from the bundled catalogue. Returns None if unknown."""
    catalogue = _load_model_catalogue()
    entry = catalogue.get(provider, {}).get(model_id)
    if entry is None:
        return None
    value = entry.get("context_window")
    return int(value) if isinstance(value, (int, float)) else None


def get_provider_models(provider: str) -> List[ModelInfo]:
    """
    Get available models for a specific provider from the bundled static catalogue.

    For local providers (Ollama, LM Studio, etc.) the catalogue is empty by design —
    models are queried at runtime via get_validated_models against the user's base URL.
    """
    if not HAS_ANY_LLM:
        return []

    if provider not in PROVIDERS:
        return []

    catalogue = _load_model_catalogue()
    models = catalogue.get(provider, {})

    if not models:
        return []

    return [
        {"value": model_id, "label": get_display_name(model_id)}
        for model_id in sorted(models.keys())
    ]


def get_provider_key_placeholder(provider: str) -> str:
    """Get the API key placeholder for a provider."""
    if provider in PROVIDERS:
        return PROVIDERS[provider]["key_placeholder"]
    return "API key..."


def get_provider_env_var(provider: str) -> str:
    """Get the environment variable name for a provider's API key."""
    if provider in PROVIDERS:
        return PROVIDERS[provider]["env_var"]
    return ""


def get_default_model(provider: str) -> str:
    """Get the default (first) model for a provider."""
    models = get_provider_models(provider)
    return models[0]["value"] if models else ""


def get_validated_models(
    provider: str,
    api_key: Optional[str] = None,
    base_url: Optional[str] = None,
) -> List[ModelInfo]:
    """
    Query the provider's /models endpoint via any-llm and return accessible models.

    For hosted providers, pass api_key. For local providers, pass base_url instead.

    Args:
        provider: Provider key (e.g., "anthropic", "openai", "ollama")
        api_key: API key for hosted providers (ignored for local)
        base_url: Base URL for local providers (ignored for hosted)

    Returns:
        List of ModelInfo dicts with 'value' and 'label' keys for valid models
    """
    import logging
    import sys
    import os

    logger = logging.getLogger(__name__)

    logger.info(f"[LLM] get_validated_models called for provider: {provider}")
    logger.info(f"[LLM] sys.frozen: {getattr(sys, 'frozen', False)}")
    logger.info(f"[LLM] SSL_CERT_FILE: {os.environ.get('SSL_CERT_FILE', 'NOT SET')}")
    logger.info(f"[LLM] REQUESTS_CA_BUNDLE: {os.environ.get('REQUESTS_CA_BUNDLE', 'NOT SET')}")

    if not HAS_ANY_LLM:
        logger.warning("[LLM] any-llm not available")
        return []

    if provider not in PROVIDERS:
        logger.warning(f"[LLM] Provider '{provider}' not in PROVIDERS")
        return []

    info = PROVIDERS[provider]
    any_llm_provider = info["any_llm_provider"]
    logger.info(f"[LLM] Using any_llm_provider: {any_llm_provider} (kind: {info['kind']})")

    kwargs = {
        "provider": any_llm_provider,
        # allow_running_loop=True lets any-llm's sync wrapper bridge to a worker
        # thread when called from inside an asyncio loop (NiceGUI button handlers
        # always are). Without it, list_models raises RuntimeError.
        "allow_running_loop": True,
    }
    if info["kind"] == "hosted":
        kwargs["api_key"] = api_key
    else:
        kwargs["api_base"] = base_url or info["base_url_default"]

    logger.info("[LLM] Calling any_llm.list_models...")
    try:
        models = any_llm.list_models(**kwargs)
    except Exception as e:
        logger.error(f"[LLM] Exception in any_llm.list_models: {type(e).__name__}: {e}")
        import traceback
        logger.error(f"[LLM] Traceback:\n{traceback.format_exc()}")
        # Re-raise so the UI can show the actual cause instead of a generic
        # "no models available" message.
        raise

    # any_llm.list_models returns Sequence[openai.types.model.Model] with .id
    model_ids = sorted({m.id for m in models if getattr(m, "id", None)})
    logger.info(f"[LLM] any_llm.list_models returned {len(model_ids)} models")

    if not model_ids:
        logger.warning("[LLM] No models returned")
        return []

    result = [
        {"value": model_id, "label": get_display_name(model_id)}
        for model_id in model_ids
    ]
    logger.info(f"[LLM] Returning {len(result)} models")
    return result
